fix_avatarImage_cover
WildCodeSchool/202302-orleans-php-project-makesense pull request #146
Opened 2023-07-18 14:01 UTC by bugBuster42

2023-07-18 14:02 UTC, JorisPineau approved these changes

2023-07-18 14:22 UTC, sblondeau requested changes

2023-07-18 14:22 UTC, sblondeau commented on assets/styles/profile.scss
> +.rounded-circle {
tu as une classe native bootstrap pour gérer ça je crois, sinon créé en une, c'est pas le role de rounded-circle

2023-07-25 13:07 UTC, JorisPineau approved these changes

2023-07-25 13:09 UTC, closed without merging