#123 2nd
WildCodeSchool/202302-orleans-php-project-makesense pull request #149
Opened 2023-07-18 15:31 UTC by Justinesvr

2023-07-18 15:32 UTC, bugBuster42 approved these changes

2023-07-18 16:28 UTC, herve-perel submitted a review, later dismissed

2023-07-19 06:52 UTC, sblondeau requested changes

2023-07-19 06:52 UTC, sblondeau commented on templates/decision/show.html.twig
> +								<img src="{{ asset('uploads/avatar/' ~ decision.user.avatar) }}" class="me-2 mb-1 d-block" alt="Portrait" style="width: 35px; height: 35px; border-radius: 50%;">
pas de style en inline

2023-07-19 06:52 UTC, sblondeau commented on templates/decision/show.html.twig
> +								<img src="{{ asset('uploads/avatar/' ~ decision.user.avatar) }}" class="me-2 mb-1 d-block" alt="Portrait" style="width: 35px; height: 35px; border-radius: 50%;">
pas de style en inline

2023-07-21 13:56 UTC, herve-perel submitted a review, later dismissed

2023-07-21 14:21 UTC, bugBuster42 approved these changes

2023-07-24 13:37 UTC, merged