page archive
WildCodeSchool/202302-orleans-php-project-makesense pull request #164
Opened 2023-07-24 14:49 UTC by herve-perel

2023-07-24 14:50 UTC, bugBuster42 submitted a review, later dismissed

2023-07-24 14:59 UTC, JorisPineau submitted a review, later dismissed

2023-07-24 15:13 UTC, sblondeau requested changes

2023-07-24 15:13 UTC, sblondeau commented on templates/decision/archive.html.twig
> +					{% if decision.status == 'Décision terminée' %}
pas en dur, tu as une constante pour aller récupérer le currentPlace

2023-07-25 13:36 UTC, Justinesvr submitted a review, later dismissed

2023-07-25 13:36 UTC, JorisPineau submitted a review, later dismissed

2023-07-25 13:37 UTC, sblondeau submitted a review, later dismissed

2023-07-25 13:45 UTC, merged