style notif
WildCodeSchool/202302-orleans-php-project-makesense pull request #167
Opened 2023-07-24 20:47 UTC by JorisPineau

2023-07-24 21:07 UTC, Justinesvr approved these changes

2023-07-25 07:00 UTC, herve-perel approved these changes

2023-07-25 07:17 UTC, Zakari-B requested changes

2023-07-25 07:17 UTC, Zakari-B commented on src/Controller/DecisionController.php
> +                // $mailer->send($email);
Pas de code commenté. Soit il sert et il n'est pas commenté soit il ne sert pas et il est effacé.

2023-07-25 07:17 UTC, Zakari-B commented on src/Controller/DecisionController.php
> +                // $mailer->send($email);
Idem

2023-07-25 07:18 UTC, sblondeau requested changes

2023-07-25 07:18 UTC, sblondeau commented on src/Controller/DecisionController.php
> +                // $mailer->send($email);
code commenté (j'ai l'impression de t'avoir déjà fait ce retour ?) et tu ne veux plus envoyer de mail du coup ?

2023-07-25 07:18 UTC, sblondeau commented on src/Controller/DecisionController.php
> +                // $mailer->send($email);
idem

2023-07-25 07:51 UTC, sblondeau approved these changes

2023-07-25 09:10 UTC, merged