start home page
WildCodeSchool/202302-orleans-php-project-makesense pull request #18
Opened 2023-06-14 15:29 UTC by Justinesvr

2023-06-14 15:30 UTC, bugBuster42 submitted a review, later dismissed

2023-06-14 21:28 UTC, sblondeau requested changes

2023-06-14 21:28 UTC, sblondeau commented on assets/images/MakesensecartographieVertPomme (1).png
pourquoi plusieurs version de la map ? dans tous les cas, renomme les fichier avec un nom clair et en anglais, là le  (1) à la fin du nom c'est pas fou ;-)

2023-06-15 07:34 UTC, MZL95 approved these changes

2023-06-15 07:35 UTC, herve-perel submitted a review, later dismissed

2023-06-15 07:35 UTC, MZL95 submitted a review, later dismissed

2023-06-15 08:36 UTC, Zakari-B requested changes

2023-06-15 08:36 UTC, Zakari-B commented on templates/home/index.html.twig
> +				<h1 class="fw-bold center">en interne</h1>
Un seul h1 sur la page.

2023-06-15 09:11 UTC, herve-perel approved these changes

2023-06-15 09:15 UTC, JorisPineau approved these changes

2023-06-15 09:17 UTC, Zakari-B approved these changes

2023-06-15 09:18 UTC, merged