a little bit style for the presentation tomorrow
WildCodeSchool/202302-orleans-php-project-makesense pull request #28
Opened 2023-06-15 19:46 UTC by Justinesvr

2023-06-16 09:58 UTC, JorisPineau submitted a review, later dismissed

2023-06-16 09:59 UTC, herve-perel submitted a review, later dismissed

2023-06-16 10:19 UTC, sblondeau requested changes

2023-06-16 10:19 UTC, sblondeau commented on assets/styles/_decisionCards.scss
> +        background-color: #FFF30D;
variable couleur

2023-06-16 10:19 UTC, sblondeau commented on assets/styles/home.scss
> +    // background-size: contain;
code commenté

2023-06-16 14:37 UTC, herve-perel approved these changes

2023-06-17 08:30 UTC, herve-perel submitted a review, later dismissed

2023-06-19 11:58 UTC, JorisPineau submitted a review, later dismissed

2023-06-19 14:28 UTC, sblondeau submitted a review, later dismissed

2023-06-20 11:33 UTC, merged