S02US11
WildCodeSchool/202302-orleans-php-project-makesense pull request #29
Opened 2023-06-17 08:28 UTC by herve-perel

2023-06-19 07:10 UTC, Justinesvr approved these changes

2023-06-19 11:58 UTC, JorisPineau approved these changes

2023-06-19 14:33 UTC, sblondeau requested changes

2023-06-19 14:33 UTC, sblondeau commented on src/Entity/Comment.php
> +    #[ORM\Column(type: Types::TEXT)]
assert NotBlank

2023-06-19 14:33 UTC, sblondeau commented on templates/decision/show.html.twig
> +								<p>{{ comment.user.email }}</p>
tu veux pas plutot afficher le nom/prénom ?

2023-06-20 10:11 UTC, herve-perel commented on templates/decision/show.html.twig
> +								<p>{{ comment.user.email }}</p>
il n'y a pas de nom/prénom dans la table

2023-06-20 10:17 UTC, Justinesvr submitted a review, later dismissed

2023-06-20 20:40 UTC, sblondeau submitted a review, later dismissed

2023-06-21 09:13 UTC, merged