S01US5
WildCodeSchool/202302-orleans-php-project-makesense pull request #3
Opened 2023-06-07 10:14 UTC by herve-perel

2023-06-07 10:28 UTC, JorisPineau submitted a review, later dismissed

2023-06-07 12:16 UTC, sblondeau requested changes

2023-06-07 12:16 UTC, sblondeau commented on src/Entity/Decision.php
> +    #[Assert\NotBlank(message: 'le champ titre est obligatoire')]
Pas de message !!!
il faut juste choisir la langue fr dans le fichier translation.yaml et c'est automatique

2023-06-07 12:16 UTC, sblondeau commented on src/Entity/Decision.php
> +    #[Assert\Length(max: 255, maxMessage: 'le titre ne doit pas dépasser {{ limit }} caractères')]
idem message

2023-06-07 12:16 UTC, sblondeau commented on src/Entity/Decision.php
> +    #[Assert\NotBlank(message: 'le champ description est obligatoire')]
idem

2023-06-07 12:16 UTC, sblondeau commented on src/Form/DecisionType.php
> +            ->add('limitDate', DateType::class, ['widget' => 'single_text', 'label' => 'Date Limite'])
tu es sur que c'est date limite ? plus startDate ? (à renommer partout du coup)

2023-06-08 07:42 UTC, JorisPineau approved these changes

2023-06-08 07:46 UTC, Justinesvr approved these changes

2023-06-08 07:46 UTC, Justinesvr approved these changes

2023-06-08 08:37 UTC, sblondeau approved these changes

2023-06-08 08:37 UTC, merged