btn_drop_admin
WildCodeSchool/202302-orleans-php-project-makesense pull request #39
Opened 2023-06-22 09:23 UTC by bugBuster42

2023-06-22 09:32 UTC, herve-perel submitted a review, later dismissed

2023-06-22 09:32 UTC, Justinesvr submitted a review, later dismissed

2023-06-22 11:49 UTC, MZL95 approved these changes

2023-06-22 21:01 UTC, sblondeau requested changes
comme discuté, partie formulaire à revoir pour mettre plutot un select (choiceType) dans une classe form dédiée

2023-07-05 11:56 UTC, JorisPineau submitted a review, later dismissed

2023-07-05 11:56 UTC, herve-perel submitted a review, later dismissed

2023-07-05 12:10 UTC, Zakari-B approved these changes

2023-07-05 13:03 UTC, merged