upload ok
WildCodeSchool/202302-orleans-php-project-makesense pull request #52
Opened 2023-07-03 14:34 UTC by Justinesvr

2023-07-03 14:35 UTC, herve-perel approved these changes

2023-07-03 14:35 UTC, JorisPineau submitted a review, later dismissed

2023-07-03 14:46 UTC, Zakari-B requested changes

2023-07-03 14:46 UTC, Zakari-B commented on config/packages/vich_uploader.yaml
> +    #    products:
Code commenté à retirer (ou adapter car tu as deux uploads possibles sur category et decision donc en toute logique deux mappings)

2023-07-03 14:46 UTC, Zakari-B commented on src/Entity/Category.php
> +
Il manque la propriété pour le fichier, par ailleurs ce n'est plus le Wild Series, utilise un nom plus pertinent que poster.

Il manquera aussi le champ updatedAt si tu veux que le changement soit pris en compte.

2023-07-03 14:46 UTC, Zakari-B commented on src/Entity/Decision.php
> +    #[Vich\UploadableField(mapping: 'poster_file', fileNameProperty: 'poster')]
Même commentaire que précédemment : poster ce n'est pas pertinent pour une décision

Il manque aussi le champ updatedAt si tu veux que le changement soit pris en compte.

2023-07-03 17:53 UTC, herve-perel submitted a review, later dismissed

2023-07-03 20:48 UTC, JorisPineau submitted a review, later dismissed

2023-07-04 15:34 UTC, bugBuster42 approved these changes

2023-07-04 16:44 UTC, herve-perel submitted a review, later dismissed

2023-07-05 15:15 UTC, Zakari-B commented on templates/components/_decisionCards.html.twig
> +							<div class="img1"><img src=""></div>
Ca sert à quoi d'avoir une balise image vide ? A retirer

2023-07-06 08:14 UTC, herve-perel approved these changes

2023-07-06 10:16 UTC, sblondeau approved these changes

2023-07-06 10:16 UTC, merged