profile
WildCodeSchool/202302-orleans-php-project-makesense pull request #53
Opened 2023-07-03 15:30 UTC by JorisPineau

2023-07-03 16:28 UTC, herve-perel submitted a review, later dismissed

2023-07-03 17:42 UTC, Justinesvr submitted a review, later dismissed

2023-07-04 09:17 UTC, sblondeau requested changes

2023-07-04 09:17 UTC, sblondeau commented on migrations/Version20230626200229.php
> +        $this->addSql('ALTER TABLE user ADD biography LONGTEXT DEFAULT NULL, ADD photo VARCHAR(255) DEFAULT NULL');
le reset du password ne fait pas partie de cette US, y a un soucis de migration là je pense

2023-07-04 09:17 UTC, sblondeau commented on migrations/Version20230627151523.php
> +    public function up(Schema $schema): void
et dans l'idéal, j'aimerais avoir un seul max fichier de migration par US, ça te permet de plus facilement vérifier que les requetes dedans correspondent bien à ce que tu veux faire

2023-07-04 10:15 UTC, herve-perel submitted a review, later dismissed

2023-07-04 10:28 UTC, Justinesvr submitted a review, later dismissed

2023-07-04 10:31 UTC, Zakari-B requested changes
Il manque un dossier uploads contenant un gitignore qui ignore tout sauf lui-même pour gérer le (non-)versionnage des uploads.

2023-07-04 10:31 UTC, Zakari-B commented on src/Controller/ProfileController.php
> +    // #[Route('/profile', name: 'profile_edit')]
Code commenté à supprimer

2023-07-04 10:31 UTC, Zakari-B commented on templates/components/_navbar.html.twig
> +									<li><a class="dropdown-item text-light bg-primary fw-light" href="{{ path('app_logout') }}">Deconnexion</a></li>
Déconnexion

2023-07-04 10:31 UTC, Zakari-B commented on templates/profile/index.html.twig
> +{% block title %}Profile{% endblock %}
Profil

2023-07-04 12:01 UTC, herve-perel submitted a review, later dismissed

2023-07-04 12:01 UTC, bugBuster42 submitted a review, later dismissed

2023-07-04 13:58 UTC, Zakari-B submitted a review, later dismissed

2023-07-04 15:30 UTC, merged