S01 us07
WildCodeSchool/202302-orleans-php-project-makesense pull request #7
Opened 2023-06-08 08:32 UTC by Justinesvr

2023-06-08 08:39 UTC, herve-perel submitted a review, later dismissed

2023-06-08 08:40 UTC, JorisPineau approved these changes

2023-06-08 09:36 UTC, Zakari-B requested changes

2023-06-08 09:36 UTC, Zakari-B commented on .env
Vous n'êtes pas sensés toucher au fichier .env

2023-06-08 09:36 UTC, Zakari-B commented on assets/styles/app.scss
> +@import "decisionCards";
il manque le _

2023-06-08 09:36 UTC, Zakari-B commented on migrations/Version20230607121925.php
> +        $this->addSql('CREATE TABLE decision (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, limit_date DATETIME NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARAC
Longtext c'est plus qu'excessif pour une description (longueur max : 2^32−1).
A ce stade c'est l'encyclopedia universalis que tu peux mettre dans ce champ...

2023-06-08 09:36 UTC, Zakari-B commented on migrations/Version20230608075802.php
Un seul fichier de migration par PR : fusionner les changements avec l'autre fichier.

2023-06-08 09:36 UTC, Zakari-B commented on src/DataFixtures/DecisionFixtures.php
> +        for ($i = 0; $i <= 12; $i++) {
Pour les fixtures, privilégier l'utilisation d'une constante de classe type NB_DECISIONS pour pouvoir choisir à la volée le nombre de fixtures que vous voulez plutôt qu'un chiffre en dur dans la boucle qui ne pourra pas être réutilisé si vous commencez à taper dans du DependantFixture.

2023-06-08 09:36 UTC, Zakari-B commented on templates/home/index.html.twig
> +		{% include 'components/_decisionCards.html.twig' %}
Le block header ne doit pas être dans le block body.

2023-06-08 09:56 UTC, Justinesvr commented on assets/styles/app.scss
> +@import "decisionCards";
ca marche sans sylvain le disait toute a l'heure

2023-06-08 09:57 UTC, Justinesvr commented on .env
pas le choix j'avais oublié de décommenter une ligne sinon ma base de donnée ne marchait pas je l'ai fait avec sylvain

2023-06-08 10:21 UTC, herve-perel approved these changes

2023-06-08 10:21 UTC, JorisPineau submitted a review, later dismissed

2023-06-08 10:26 UTC, herve-perel submitted a review, later dismissed

2023-06-08 10:26 UTC, JorisPineau approved these changes

2023-06-08 11:50 UTC, sblondeau requested changes

2023-06-08 11:50 UTC, sblondeau commented on assets/styles/app.scss
> +@import "decisionCards";
j'ai dis "je crois que ça marche sans" :D  
mais tu dois bien voir si c'est le cas ;-)

2023-06-08 11:50 UTC, sblondeau commented on src/Controller/HomeController.php
> +            'decisions' => $decisionRepository->findAll(),
c'est pas mieux si c'est trier par  start_date de la plus récente à la plus ancienne ?

2023-06-08 11:50 UTC, sblondeau commented on src/Entity/Decision.php
> +    #[Assert\Length(max: 255)]
je sais que vous vous êtes un peu "marché dessus" avec Hervé, donc laisse comme ça, mais dans l'idée, si tu gères que l'affichage des décisions, tu n'as pas à gérer tout de suite la validation et donc les #Assert

par contre Hervé s'il gère le CREATE doit le faire à ce moment ;-)

2023-06-08 11:50 UTC, sblondeau commented on templates/components/_decisionCards.html.twig
> +	</div>
ce n'est pas vraiment une navbar ? en tout cas si c'est le cas ça doit etre une balise nav
mais ce qui me dérange le plus c'est les button, or ça devrait etre des liens non ? Je ne suis pas sur que vous sachiez bien ce que vous voulez faire de ces boutons...

2023-06-08 11:58 UTC, Justinesvr commented on assets/styles/app.scss
> +@import "decisionCards";
bah c'est le cas

2023-06-08 12:20 UTC, JorisPineau submitted a review, later dismissed

2023-06-08 12:20 UTC, herve-perel submitted a review, later dismissed

2023-06-08 13:03 UTC, sblondeau submitted a review, later dismissed

2023-06-09 08:37 UTC, Zakari-B approved these changes

2023-06-09 08:37 UTC, merged