avatar picture
WildCodeSchool/202302-orleans-php-project-makesense pull request #77
Opened 2023-07-10 14:32 UTC by bugBuster42

2023-07-10 14:33 UTC, JorisPineau approved these changes

2023-07-10 14:34 UTC, herve-perel approved these changes

2023-07-10 15:10 UTC, sblondeau requested changes

2023-07-10 15:10 UTC, sblondeau commented on composer.json
> +        "guzzlehttp/guzzle": "^7.7",
il te sert à quoi guzzle là ?

2023-07-10 15:10 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +        $user->setAvatar("https://randomuser.me/api/portraits/men/1.jpg");
randomuser est une api sympa pour récup des images, mais dans l'utilisation ça ne me va pas car tu ne simules pas un upload là, tu met une url en dur. 
voir mon livecoding pour que les images soient copiées / collées dans le dossier upload

2023-07-12 09:05 UTC, Justinesvr approved these changes

2023-07-12 09:19 UTC, JorisPineau submitted a review, later dismissed

2023-07-12 10:16 UTC, Zakari-B submitted a review, later dismissed

2023-07-13 14:55 UTC, merged