Img category
WildCodeSchool/202302-orleans-php-project-makesense pull request #78
Opened 2023-07-11 15:33 UTC by Justicesvr

2023-07-11 16:29 UTC, herve-perel submitted a review, later dismissed

2023-07-12 07:00 UTC, bugBuster42 approved these changes

2023-07-12 08:14 UTC, sblondeau requested changes
les images sont trop grosses ! vu la taille ou tu les affiche, 100ko est largement suffisant

2023-07-12 13:16 UTC, herve-perel approved these changes

2023-07-12 13:57 UTC, sblondeau submitted a review, later dismissed

2023-07-12 15:33 UTC, merged