S01US6
WildCodeSchool/202302-orleans-php-project-makesense pull request #8
Opened 2023-06-08 13:26 UTC by herve-perel

2023-06-08 13:43 UTC, Justinesvr approved these changes

2023-06-08 14:16 UTC, Justinesvr submitted a review, later dismissed

2023-06-08 14:32 UTC, JorisPineau submitted a review, later dismissed

2023-06-08 15:12 UTC, Zakari-B requested changes

2023-06-08 15:12 UTC, Zakari-B commented on templates/decision/_delete_form.html.twig
> +    <button class="btn btn-light text-primary my-2 border border-secondary rounded-pill">Delete</button>
En français.

2023-06-08 15:12 UTC, Zakari-B commented on templates/decision/edit.html.twig
> +		{{ include('decision/_form.html.twig', {'button_label': 'Update'}) }}
Idem.

2023-06-08 15:28 UTC, Justinesvr submitted a review, later dismissed

2023-06-08 15:28 UTC, bugBuster42 submitted a review, later dismissed

2023-06-09 09:14 UTC, Justinesvr approved these changes

2023-06-09 09:14 UTC, JorisPineau approved these changes

2023-06-09 10:07 UTC, Zakari-B approved these changes

2023-06-09 10:07 UTC, merged