ajout de condition bouton workflow
WildCodeSchool/202302-orleans-php-project-makesense pull request #83
Opened 2023-07-12 17:39 UTC by herve-perel

2023-07-13 06:59 UTC, Justinesvr approved these changes

2023-07-13 07:59 UTC, bugBuster42 approved these changes

2023-07-13 08:00 UTC, Justinesvr submitted a review, later dismissed

2023-07-13 08:05 UTC, sblondeau requested changes
à discuter ensemble

2023-07-13 08:05 UTC, sblondeau commented on templates/components/_workflowStatus.html.twig
> +{% if decision.votes|filter(vote => vote.voting == -1)|length < decision.votes|length * 70 / 100 and decision.votes|length > 3 %}
il va falloir utiliser des constantes

2023-07-13 08:05 UTC, sblondeau commented on templates/components/_workflowStatus.html.twig
> +{% if decision.votes|filter(vote => vote.voting == -1)|length < decision.votes|length * 70 / 100 and decision.votes|length > 3 %}
ça fait beaucoup de logique dans ton Twig, à voir si y aurait pas un service à creer plutot, on en discute

2023-07-13 08:05 UTC, sblondeau commented on templates/components/_workflowStatus.html.twig
> +		<a href="{{ path('app_change', {'id': decision.id, 'toStatus': 'to_decision_opened_accepted'}) }}" class="btn btn-primary fw-bold rounded-pill mb-5 mx-5 mt-3">Passer au statut accepté</a>
idem là ça change ta bdd au final ? plutot un form en POST du coup

2023-07-14 19:15 UTC, bugBuster42 approved these changes

2023-07-17 07:33 UTC, JorisPineau approved these changes

2023-07-17 07:40 UTC, sblondeau requested changes

2023-07-17 07:40 UTC, sblondeau commented on src/Controller/DecisionController.php
>          Decision $decision,
ajouter method POST pour cette methode

2023-07-17 07:40 UTC, sblondeau commented on src/Service/WorkflowAdvancement.php
> +    public function firstStepStatus(Decision $decision): ?string
hum pas certain de comprendre
pour moi tu ne dois avoir qu'une seule methode getStepStatus qui te renvoie la string du nom du step

2023-07-17 10:41 UTC, bugBuster42 submitted a review, later dismissed

2023-07-17 11:56 UTC, JorisPineau approved these changes

2023-07-17 11:56 UTC, Justinesvr approved these changes

2023-07-17 12:02 UTC, sblondeau submitted a review, later dismissed

2023-07-17 12:12 UTC, merged